name: Build Crate

on:
  workflow_call:
    inputs:
      crate-name:
        required: true
        type: string
      version:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: .
      toolchain:
        required: false
        type: string
        default: stable
      ref:
        required: false
        type: string

jobs:
  # Build sources for every OS
  github_build:
    name: Build release binary (${{ matrix.target }})
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            name: aarch64-unknown-linux-musl.tar.gz
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: x86_64-unknown-linux-gnu.tar.gz
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: x86_64-unknown-linux-musl.tar.gz
          - target: x86_64-apple-darwin
            os: macOS-latest
            name: x86_64-apple-darwin.tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: x86_64-pc-windows-msvc.zip
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Setup | Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
          target: ${{ matrix.target }}

      - name: Setup | cross
        if: endsWith(matrix.target, '-unknown-linux-musl')
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build | Build
        if: ${{ !endsWith(matrix.target, '-unknown-linux-musl') }}
        working-directory: ${{ inputs.working-directory }}
        run: cargo build --release --target ${{ matrix.target }} --message-format json > build_log.json

      - name: Build | Build (musl)
        if: endsWith(matrix.target, '-unknown-linux-musl')
        working-directory: ${{ inputs.working-directory }}
        run: cross build --release --target ${{ matrix.target }} --message-format json > build_log.json

      - name: "Post Setup | Get workspace folder"
        id: workspace_folder
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: |
          workspace_manifest=$(cargo locate-project --workspace --message-format plain)
          workspace_folder=$(dirname "$workspace_manifest")
          echo "Located workspace folder: $workspace_folder"
          echo "workspace_folder=$workspace_folder" >> $GITHUB_OUTPUT

      - name: "Post Setup | Extract binary path"
        id: binary_path
        shell: python
        working-directory: ${{ inputs.working-directory }}
        env:
          IS_CROSS: ${{ endsWith(matrix.target, '-unknown-linux-musl') }}
          WORKSPACE_FOLDER: ${{ steps.workspace_folder.outputs.workspace_folder }}
        run: |
          import json
          import os

          binary_path = None
          is_cross = os.environ["IS_CROSS"] == "true"
          workspace_folder = os.environ["WORKSPACE_FOLDER"]

          with open("build_log.json", "r") as f:
              for line in f:
                  try:
                      msg = json.loads(line)
                  except json.JSONDecodeError:
                      continue

                  reason = msg.get("reason")
                  executable = msg.get("executable")
                  is_test = msg.get("profile", {}).get("test", False)

                  if reason == "compiler-artifact" and executable and not is_test:
                      binary_path = msg["executable"]
                      break
              else:
                  print("No binary path found in build log")
                  exit(1)

          # Stuff compiled in cross is compiled in a container and the target folder is at root
          if is_cross:
              print(f"Cross-compilation detected, adjusting binary path for cross")
              binary_path = workspace_folder.removesuffix("/") + "/" + binary_path.removeprefix("target/")

          print(f"Resolved binary path: {binary_path}")

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"binary_path={binary_path}\n")
              f.write(f"binary_dir={os.path.dirname(binary_path)}\n")

      - name: Post Setup | Prepare artifacts [Windows]
        if: matrix.os == 'windows-latest'
        working-directory: ${{ steps.workspace_folder.outputs.workspace_folder }}
        run: |
          mkdir target/artifacts
          7z a target/artifacts/${{ inputs.crate-name }}-${{ inputs.version }}-${{ matrix.name }} ${{ steps.binary_path.outputs.binary_path }}

      - name: Post Setup | Prepare artifacts [-nix]
        if: matrix.os != 'windows-latest'
        working-directory: ${{ steps.workspace_folder.outputs.workspace_folder }}
        run: |
          mkdir target/artifacts
          tar czvf target/artifacts/${{ inputs.crate-name }}-${{ inputs.version }}-${{ matrix.name }} ${{ steps.binary_path.outputs.binary_path }}

      - name: Post Setup | Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.crate-name }}-${{ inputs.version }}-${{ matrix.name }}
          path: ${{ steps.workspace_folder.outputs.workspace_folder }}/target/artifacts/*
          overwrite: true
          retention-days: 1
