name: Build Crate

on:
  workflow_call:
    inputs:
      crate-name:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: .
      toolchain:
        required: false
        type: string
        default: stable
      ref:
        required: false
        type: string

jobs:
  # Build sources for every OS
  github_build:
    name: Build release binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            name: aarch64-unknown-linux-musl.tar.gz
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: x86_64-unknown-linux-gnu.tar.gz
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: x86_64-unknown-linux-musl.tar.gz
          - target: x86_64-apple-darwin
            os: macOS-latest
            name: x86_64-apple-darwin.tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: x86_64-pc-windows-msvc.zip
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Setup | Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
          target: ${{ matrix.target }}

      - name: Setup | cross
        if: endsWith(matrix.target, '-unknown-linux-musl')
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build | Build
        if: ${{ !endsWith(matrix.target, '-unknown-linux-musl') }}
        working-directory: ${{ inputs.working-directory }}
        run: cargo build --release --target ${{ matrix.target }} --message-format json > build_log.json

      - name: Build | Build (musl)
        if: endsWith(matrix.target, '-unknown-linux-musl')
        working-directory: ${{ inputs.working-directory }}
        run: cross build --release --target ${{ matrix.target }} --message-format json > build_log.json

      - name: "Post Setup | Extract tag name"
        id: extract_tag
        shell: bash
        run: |
          tag=$(echo ${GITHUB_REF#refs/tags/})
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: "Post Setup | Extract binary path"
        id: binary_path
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: |
          binary_path=$(
            jq -r '
              first(
                select(
                  .reason == "compiler-artifact"
                  and .executable != null
                  and .profile.test == false
                )
                | .executable
              )
            ' build_log.json
          )

          if [ -z "$binary_path" || $binary_path == "null" ]; then
            echo "No binary path found in build log"
            exit 1
          fi

          echo "Located binary path: $binary_path"

          echo "binary_path=$binary_path" >> $GITHUB_OUTPUT
          echo "binary_dir=$(dirname "$binary_path")" >> $GITHUB_OUTPUT

      - name: "Post Setup | Get workspace folder"
        id: workspace_folder
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: |
          workspace_manifest=$(cargo locate-project --workspace --message-format plain)
          workspace_folder=$(dirname "$workspace_manifest")
          echo "Located workspace folder: $workspace_folder"
          echo "workspace_folder=$workspace_folder" >> $GITHUB_OUTPUT

      - name: Post Setup | Prepare artifacts [Windows]
        if: matrix.os == 'windows-latest'
        working-directory: ${{ steps.workspace_folder.outputs.workspace_folder }}
        run: |
          mkdir target/stage
          7z a target/stage/${{ inputs.crate-name }}-${{ steps.extract_tag.outputs.tag }}-${{ matrix.name }} ${{ steps.binary_path.outputs.binary_path }}

      - name: Post Setup | Prepare artifacts [-nix]
        if: matrix.os != 'windows-latest'
        working-directory: ${{ steps.workspace_folder.outputs.workspace_folder }}
        run: |
          mkdir target/stage
          tar czvf target/stage/${{ inputs.crate-name }}-${{ steps.extract_tag.outputs.tag }}-${{ matrix.name }} ${{ steps.binary_path.outputs.binary_path }}

      - name: Post Setup | Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.crate-name }}-${{ steps.extract_tag.outputs.tag }}-${{ matrix.name }}
          path: ${{ steps.workspace_folder.outputs.workspace_folder }}/target/stage/*
          overwrite: true
          retention-days: 1
