name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: stable
  RUSTFLAGS: -D warnings # Fail on warnings

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Run tests for ${{ matrix.crate.name }}"
    strategy:
      fail-fast: false
      matrix:
        crate:
          - name: sosaku
            is_python: false
          - name: sosaku-cli
            is_python: false
          - name: sosaku-py
            is_python: true
    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v6

      - name: Setup | Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        if: matrix.crate.is_python == true
        with:
          version: "0.11"
          python-version: "3.10"

      - name: Build | Compile Project
        working-directory: ./${{ matrix.crate.name }}
        run: |
          if [ "${{ matrix.crate.is_python }}" = "true" ]; then
              uv sync --dev
          else
              cargo build --verbose
          fi

      - name: Run | Tests
        working-directory: ./${{ matrix.crate.name }}
        run: |
          if [ "${{ matrix.crate.is_python }}" = "true" ]; then
              uv run pytest tests -v
          else
              cargo test --verbose
          fi

  clippy:
    runs-on: ubuntu-latest
    name: "Run clippy"
    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v6

      - name: Setup | Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy

      - name: Run | Clippy
        run: cargo clippy --verbose

  format:
    runs-on: ubuntu-latest
    name: "Check formatting"
    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v6

      - name: Setup | Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
