name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: stable
  RUSTFLAGS: -D warnings # Fail on warnings

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Run tests for ${{ matrix.crate.name }}"
    strategy:
      fail-fast: false
      matrix:
        crate:
          - name: sifter
          - name: sifter-cli
    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v6

      - name: Setup | Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt

      - name: Build | Compile Project
        working-directory: ./${{ matrix.crate.name }}
        run: cargo build --verbose

      - name: Run | Tests
        working-directory: ./${{ matrix.crate.name }}
        run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest
    name: "Run clippy"
    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v6

      - name: Setup | Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy

      - name: Run | Clippy
        run: cargo clippy --verbose

  format:
    runs-on: ubuntu-latest
    name: "Check formatting"
    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v6

      - name: Setup | Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
