# Based on https://github.com/tommilligan/mdbook-admonish/blob/main/.github/workflows/deploy.yml

name: Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v0.1.0)"
        required: true

env:
  RUST_VERSION: stable
  UV_VERSION: 0.11

jobs:
  init:
    name: Initialize Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.parse_version.outputs.version }}
      major: ${{ steps.parse_version.outputs.major }}
      minor: ${{ steps.parse_version.outputs.minor }}
      patch: ${{ steps.parse_version.outputs.patch }}
      rust_version: ${{ steps.env_vars.outputs.rust_version }}
      uv_version: ${{ steps.env_vars.outputs.uv_version }}
    steps:
      - name: Reoutput env
        id: env_vars
        run: |
          echo "rust_version=${{ env.RUST_VERSION }}" >> $GITHUB_OUTPUT
          echo "uv_version=${{ env.UV_VERSION }}" >> $GITHUB_OUTPUT

      - name: Parse version
        id: parse_version
        shell: bash
        env:
          VERSION: ${{ inputs.version || github.ref_name }}
        run: |
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in the format vX.Y.Z"
            exit 1
          fi

          version=$(echo $VERSION | tr -d 'v')
          major=$(echo $VERSION | cut -d. -f1 | tr -d 'v')
          minor=$(echo $VERSION | cut -d. -f2)
          patch=$(echo $VERSION | cut -d. -f3)

          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT
          echo "patch=$patch" >> $GITHUB_OUTPUT

      # Prevent creating releases from non-default branches when manually triggered
      - name: Check if on default branch
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          CURRENT_BRANCH: ${{ github.ref_name }}
        run: |
          if [ "$CURRENT_BRANCH" != "$DEFAULT_BRANCH" ]; then
            echo "Error: Current branch $CURRENT_BRANCH is not the default branch $DEFAULT_BRANCH"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-tags: true

      # Prevent clobbering new tags pushed to old releases
      - name: Check if tag is on default branch
        if: github.event_name != 'workflow_dispatch'
        shell: bash
        env:
          TAG: ${{ github.ref_name }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          tag_commit="$(git rev-parse "${TAG}^{}")"
          branch_head="$(git rev-parse "origin/${DEFAULT_BRANCH}")"

          if [ "$tag_commit" != "$branch_head" ]; then
            echo "Error: Tag $TAG is not the tip of the $DEFAULT_BRANCH branch"
            exit 1
          fi

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install cargo-edit
        run: cargo install cargo-edit --no-default-features --features "set-version"

      - name: Bump version
        run: cargo set-version ${{ steps.parse_version.outputs.version }}

      - name: Push changes
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git commit -am "Bump version to ${{ steps.parse_version.outputs.version }}" || exit 0
          git tag -f v${{ steps.parse_version.outputs.version }}
          git push origin ${{ github.event.repository.default_branch }} --tags --force

  build_crate_bins:
    name: Build crate binaries
    needs: init
    uses: ./.github/workflows/build-crate-bin.yaml
    strategy:
      fail-fast: true
      matrix:
        crate:
          - "sosaku-cli"
    with:
      crate-name: ${{ matrix.crate }}
      working-directory: ${{ matrix.crate }}
      version: ${{ needs.init.outputs.version }}
      ref: ${{ github.event.repository.default_branch }}

  build_py_wheels:
    name: Build Python wheels
    needs: init
    uses: ./.github/workflows/build-py-wheel.yaml
    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        crate:
          - "sosaku-py"
        py-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    with:
      package-name: ${{ matrix.crate }}
      working-directory: ${{ matrix.crate }}
      python-version: ${{ matrix.py-version }}
      ref: ${{ github.event.repository.default_branch }}

  github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [init, build_crate_bins, build_py_wheels]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts
          pattern: "!wheels-*" # Exclude wheels

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # body_path: RELEASE.md
          files: artifacts/**/*
          overwrite_files: true
          tag_name: v${{ needs.init.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: github_release
    permissions:
      # Use to sign the release artifacts
      id-token: write
      # Used to upload release artifacts
      contents: write
      # Used to generate artifact attestation
      attestations: write
    steps:
      - name: Download run artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: "wheels-*"

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: "wheels-*/*"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}

      - name: Publish to PyPI
        run: uv publish 'wheels-*/*'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  # Upload to crates.io
  publish-crates-io:
    name: Publish to crates.io
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Publish crate
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
